# Force single-process Loki
deploymentMode: SingleBinary

# Build Loki's config from structured values (do NOT set loki.config:)
loki:
  auth_enabled: false

  # Filesystem storage for local/minikube
  storage:
    type: filesystem
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules

  # TSDB schema using filesystem
  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

# Single binary pod count
singleBinary:
  replicas: 1

# Persist data so restarts don't erase logs
persistence:
  enabled: true
  size: 10Gi
  accessModes: [ "ReadWriteOnce" ]
  # use your cluster's StorageClass (minikube often 'standard' or 'standard-rwo')
  # storageClass: standard

# Optional: turn off extras you don't need locally
gateway:
  enabled: false
resultsCache:
  enabled: false
chunksCache:
  enabled: false
ruler:
  enabled: false

grafana:
  enabled: false   # don’t install Grafana again
promtail:
  enabled: true
