apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-datasource
  namespace: monitoring   # same namespace where grafana is installed
  labels:
    grafana_datasource: "1"  # important: tells Grafana sidecar to load this
data:
  loki-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-stack.monitoring.svc.cluster.local:3100
        isDefault: false
        jsonData:
          httpHeaderName1: X-Scope-OrgID
        secureJsonData:
          httpHeaderValue1: 1
        orgId: 1